services:
  jenkins:
    build: ./
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins2
    volumes:
    - ./jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube2
    ports:
      - 9000:9000