FROM openjdk:21-bookworm

RUN mkdir -p /root/.ssh

COPY ./id_rsa.pub /root/.ssh/authorized_keys

RUN chmod 600 /root/.ssh/authorized_keys

RUN apt-get update && apt-get install -y \
    openssh-server \
    python3 \
    python3-pip \
    python3-apt \
    curl \
    gnupg

RUN mkdir /var/run/sshd

EXPOSE 22
EXPOSE 80

CMD ["/usr/sbin/sshd", "-D"]
