FROM alpine:3.11

RUN apk add --no-cache openssh-client ansible git sshpass

RUN mkdir -p /root/.ssh

COPY ./id_rsa /root/.ssh/id_rsa

RUN chmod 600 /root/.ssh/id_rsa

COPY ./ansible /ansible

WORKDIR /ansible

CMD [ "" ]
