---
- name: Fix SSH known_hosts for debian-work
  hosts: localhost
  tasks:
    - name: Add SSH key to known_hosts
      ansible.builtin.known_hosts:
        path: "~/.ssh/known_hosts"
        name: "172.18.0.2"
        key: "{{ lookup('pipe', 'ssh-keyscan -H 172.18.0.2') }}"
        state: present

- name: Deploy Java app with Nginx and OpenJDK
  hosts: all
  roles:
    - install_dependencies
    - deploy_files
    - start_java_app
